export default COLORS = {
    appBackground: "#FFFFFF",
    drawerMenu: "#222222",
    appSeparator: "#424242",
    drawerMenuTitle: "white",
    drawerMenuActiveItemText: "#cccccc",
    drawerMenuInactiveActiveItemText: "#424242",
    newsFeedTagText: "white",
    newsFeedTitle: "black",
    newsFeedContent:"black",
    newsFeedTagTodas: "#303235",
    navBarIconTint: "#FFFFFF",
    navBarText: "white",
    navBarBackground: "#222222",
    priceTableBorderColor: '#424242',
    calendarItemBackground: '#FFFFFF',
    calendarItemTitle: '#000000',
    submitButton: '#437db7',
    submitButtonBorder: '#306aa5',
    submitButtonText: '#FFFFFF',
    feedbackContainerBackground: '#fffad8',
    feedbackContainerBorder: '#fcf5c9',
    feedbackText: '#000000',
    serviceAccordionActive: '#f5fcff',
    serviceAccordionInactive: '#f5fcff',
    serviceAccordionBorderBottom: 'gray',
    serviceTitle: '#000000'
}