export default COLORS = {
    appBackground: "#FFFFFF",
    drawerMenu: "#222222",
    appSeparator: "#424242",
    drawerMenuTitle: "white",
    drawerMenuActiveItemText: "#cccccc",
    drawerMenuInactiveActiveItemText: "#424242",
    newsFeedTagText: "white",
    newsFeedTitle: "black",
    newsFeedContent:"black",
    newsFeedTagTodas: "#303235",
    navBarIconTint: "#FFFFFF",
    navBarText: "white",
    navBarBackground: "#222222",
}